alter table public.profiles add column if not exists role text not null default 'learner';

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

grant execute on function public.is_admin() to authenticated;

create table if not exists public.sentences (
  id bigint generated by default as identity primary key,
  english text not null,
  level text not null,
  grammar text not null,
  category text not null,
  pattern text not null,
  similar_example text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.sentences enable row level security;

drop policy if exists "Public can read active sentences" on public.sentences;
create policy "Public can read active sentences" on public.sentences
for select using (is_active = true or public.is_admin());

drop policy if exists "Admins can insert sentences" on public.sentences;
create policy "Admins can insert sentences" on public.sentences
for insert to authenticated with check (public.is_admin());

drop policy if exists "Admins can update sentences" on public.sentences;
create policy "Admins can update sentences" on public.sentences
for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can delete sentences" on public.sentences;
create policy "Admins can delete sentences" on public.sentences
for delete to authenticated using (public.is_admin());

-- Replace the email below with your own login email, then run this statement once.
-- update public.profiles set role = 'admin' where id = (select id from auth.users where email = 'YOUR_EMAIL@example.com');